spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bms?serverTimezone=UTC
    username: root
    password: '{cipher}9ebe11f4ec06e69fa96b76d876ff06005935a2becb3297f6c833b4946c2f6044'
    driver-class-name: com.mysql.jdbc.Driver
