zuul:
  ignored-services: '*'
  prefix: /api
  routes:
    BookService: /Getbook/**
hystrix:
  command：
    default：
      execution：
        isolation：
          thread：
            timeoutInMilliseconds = 4000
